default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: bus_control_development

test:
  <<: *default
  database: bus_control_test

production:
  <<: *default
  database: bus_control_production
  username: bus_control
  password: <%= ENV['BUS_CONTROL_DATABASE_PASSWORD'] %>
